### ISSUE TITLE
Allow implementing custom brush types

### ISSUE THREAD

**Issue by mysticfall** [SixLabors/ImageSharp.Drawing#20]
For now, `IBrush` is supposed to return an instance of `BrushApplicator`, but both its constructor and indexer are defined with an `internal` modifier, which makes it practically impossible to create a custom brush implementation.

It can prevent users from adopting ImageSharp in case they need a type of brush that the library doesn't support, as described in SixLabors/ImageSharp#969, for example.

**Comment by antonfirsov** [comment]
We need to make `BrushApplicator` constructor `protected`:
https://github.com/SixLabors/ImageSharp.Drawing/blob/d8960b8e2e55875d2c4f990f5fc439b846af1230/src/ImageSharp.Drawing/Processing/BrushApplicator.cs#L23

We shall consider changing `Apply` to consume `RowInterval` instead of `y`:

https://github.com/SixLabors/ImageSharp.Drawing/blob/d8960b8e2e55875d2c4f990f5fc439b846af1230/src/ImageSharp.Drawing/Processing/BrushApplicator.cs#L77

**Comment by JimBobSquarePants** [comment]
Yeah if we can use RowInterval that’d be much preferable

**Comment by JimBobSquarePants** [comment]
@antonfirsov Found issues with using `RowInterval`. Looks like we're stuck working one line at a time.

https://github.com/SixLabors/ImageSharp.Drawing/blob/423bf06a6b8bfce3a9991bede8af3e550c6742ca/src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor%7BTPixel%7D.cs#L155-L160

https://github.com/SixLabors/ImageSharp.Drawing/blob/423bf06a6b8bfce3a9991bede8af3e550c6742ca/src/ImageSharp.Drawing/Processing/Processors/Drawing/FillRegionProcessor%7BTPixel%7D.cs#L87-L132
