### ISSUE TITLE
Support blending for Fill operations when targeting Rgb24 image

### ISSUE THREAD

**Issue by atruskie** [SixLabors/ImageSharp.Drawing#38]
Please add support for blending colors with an alpha component when using the fill operation by
> passing the pixel format of the brush to the processor.

Code example:

```csharp
[TestMethod]
public void Test()
{
    var image = new Image<Rgb24>(Configuration.Default, 100, 100, Color.Black);

    image.Mutate(x => x.Fill(Color.Red.WithAlpha(0.5f)));

    // 50% blended with black
    var expectedColor = new Rgb24(128, 0, 0);

    // expected result
    //Assert.AreEqual(expectedColor, image[50, 50]);
    // fails with:     Assert.AreEqual failed. Expected:<Rgb24(128, 0, 0)>. Actual:<Rgb24(255, 0, 0)>.

    // Actual (buggy?) result
    Assert.AreEqual(new Rgb24(255, 0, 0), image[50, 50]);
}
```

The above example fails with ImageSharp.Drawing 1.0.0-unstable0421

# Gitter context

<details>
<summary>...copy of chat log...</summary>

> @atruskie: Hi all, quick question about blending modes. When drawing on an Rgb24 image, I'd expect colors/brushes/pens with that are not opaque (alpha < 1) to automatically blend. But this doesn't seem to be the case. Am I missing something here?

> @JimBobSquarePants : @atruskie You're expecting the wrong thing.
>
>You have a 24bit pixel image. Adjusting the opacity of the color you are blending will not make a difference since it will be converted to Rgb24. By default the GraphicsOptions used by filling will have a color blending mode of PixelColorBlendingMode.Normal and alpha composition mode of PixelAlphaCompositionMode.SrcOverwhich will simply paint the color over the background since there is no alpha component.
>
>To get your expected result the background should have an alpha component. So use Rgba32.
>
>You should also dispose of your images once you have finished with them.

> @atruskie: @JimBobSquarePants, thanks for the response. I really don't need an Rgba32 image. The image itself doesn't need any transparency.
>
>Given that IImageProcessingContext is meant to be a pixel agnostic drawing interface, my question becomes, how do I fill a region with a 50% opacity colour? So setting BlendPercentage = 0.5f in graphics options does a fill with a blend. I admittedly don't understand the effects of PixelColorBlendingMode and PixelAlphaCompositionMode but I tried various values and it did not seem to have any effect.
>
>However, may I suggest what I was expecting should work? Here's why:
>
> 1. System.Drawing and SkiaSharp act how I expect (caveat: I am no expert on anything). Example: https://gist.github.com/atruskie/02f6fb35d6967c57ed543d109e83736e
> 2. If a Rgb24 pixel blender encounters an Rgba32 pixel, it blends with the rgba32's opacity as I expect, so why doesn't that symmetry hold for image&fill? Example: https://gist.github.com/atruskie/f12f22830f79ba42943433edee964a53

> @JimBobSquarePants:
>@atruskie
>
>> Given that IImageProcessingContext is meant to be a pixel agnostic drawing interface
>
>This means that you can use any TPixel input. Not that the result would be the same. For example, changing the alpha component via a color matrix on a pixel format with no alpha component will have no effect. I can see how that would be confusing though.
>
>Your second point is very pertinent here. Our internal PixelBlender API allows mixing different pixel formats but Fill does not. We should update our API to allow for the behavior you expect by passing the pixel format of the brush to the processor.
>
>Could you please raise a feature request in the ImageSharp.Drawing repository and we can have a look at getting that implmented. Thanks!

</details>

**Comment by tocsoft** [comment]
Hmm... I would expect that to 'just work'.

My guess is we are not translating the throwing alpha channel of the Vector4 away during conversion from Vector4 => Rgba24.

@JimBobSquarePants I would, for example, expect `Rgba32(255,255,255, 128)` == `Rgb24(128, 128, 128)` that's what's intuitive for the operations in my opinion... which is the equivalent of what's happening above.

**Comment by JimBobSquarePants** [comment]
@tocsoft That would contradict how things like  work like converting a png to a jpeg. We, and other libraries simply drop the alpha. 

What we need to do is pass the `Color` we input in to the blender in a pixel format that supports the alpha component. The fix is easy I think.... Instead of using `TPixel` for the brush pixel format we use `RgbaVector` and use the overload for blend that allows different pixel formats.

**Comment by JimBobSquarePants** [comment]
Ok.... This code returns the expected result however I'm not sure this is the correct fix. What is the indexer used for? How do we ensure application is consistent across all brushes?

``` c#
/// <summary>
/// The solid brush applicator.
/// </summary>
private class SolidBrushApplicator<TPixel> : BrushApplicator<TPixel>
    where TPixel : unmanaged, IPixel<TPixel>
{
    private bool isDisposed;
    private IMemoryOwner<RgbaVector> colorVectors;

    /// <summary>
    /// Initializes a new instance of the <see cref="SolidBrushApplicator{TPixel}"/> class.
    /// </summary>
    /// <param name="configuration">The configuration instance to use when performing operations.</param>
    /// <param name="options">The graphics options.</param>
    /// <param name="source">The source image.</param>
    /// <param name="color">The color.</param>
    public SolidBrushApplicator(
        Configuration configuration,
        GraphicsOptions options,
        ImageFrame<TPixel> source,
        Color color)
        : base(configuration, options, source)
    {
        this.Colors = configuration.MemoryAllocator.Allocate<TPixel>(source.Width);
        this.colorVectors = configuration.MemoryAllocator.Allocate<RgbaVector>(source.Width);
        this.Colors.Memory.Span.Fill(color.ToPixel<TPixel>());
        this.colorVectors.Memory.Span.Fill(color.ToPixel<RgbaVector>());
    }

    /// <summary>
    /// Gets the colors.
    /// </summary>
    protected IMemoryOwner<TPixel> Colors { get; private set; }

    /// <inheritdoc/>
    internal override TPixel this[int x, int y] => this.Colors.Memory.Span[x];

    /// <inheritdoc />
    protected override void Dispose(bool disposing)
    {
        if (this.isDisposed)
        {
            return;
        }

        if (disposing)
        {
            this.Colors.Dispose();
            this.colorVectors.Dispose();
        }

        this.Colors = null;
        this.colorVectors = null;
        this.isDisposed = true;
    }

    /// <inheritdoc />
    internal override void Apply(Span<float> scanline, int x, int y)
    {
        Span<TPixel> destinationRow = this.Target.GetPixelRowSpan(y).Slice(x);

        // constrain the spans to each other
        if (destinationRow.Length > scanline.Length)
        {
            destinationRow = destinationRow.Slice(0, scanline.Length);
        }
        else
        {
            scanline = scanline.Slice(0, destinationRow.Length);
        }

        Configuration configuration = this.Configuration;
        MemoryAllocator memoryAllocator = configuration.MemoryAllocator;

        if (this.Options.BlendPercentage == 1F)
        {
            this.Blender.Blend<RgbaVector>(configuration, destinationRow, destinationRow, this.colorVectors.Memory.Span, scanline);
        }
        else
        {
            using (IMemoryOwner<float> amountBuffer = memoryAllocator.Allocate<float>(scanline.Length))
            {
                Span<float> amountSpan = amountBuffer.Memory.Span;

                for (int i = 0; i < scanline.Length; i++)
                {
                    amountSpan[i] = scanline[i] * this.Options.BlendPercentage;
                }

                this.Blender.Blend<RgbaVector>(
                    configuration,
                    destinationRow,
                    destinationRow,
                    this.colorVectors.Memory.Span,
                    amountSpan);
            }
        }
    }
}
```

**Comment by antonfirsov** [comment]
>  I would, for example, expect `Rgba32(255,255,255, 128)` == `Rgb24(128, 128, 128)` that's what's intuitive for the operations in my opinion

> We, and other libraries simply drop the alpha.

Maybe we want to make this configurable?

```C#
public class Configuration
{
    bool PreferAutomaticAlphaPremultiplication { get; set; } = false;
}
```

**Comment by JimBobSquarePants** [comment]
You know it never even occurred to me that the issue was premultiplication (_or the lack of_) back then.

**Comment by antonfirsov** [comment]
There is a non-trivial design question around using a different pixel format for `BrushApplicator<T>`.
`BrushApplicator<RgbaVector>` might be too slow (in long term we need integer arithmetics for blending). We can use `BrushApplicator<Rgba32>`, but what if the input is `Rgba64`? Etc..

We should check what what does Skia and System.Drawing do when drawing with `Color(255,255,255, 128)` on an `Rgb24` image. If it behaves the same as we do, I would say ... wontfix.

**Comment by JimBobSquarePants** [comment]
I checked a while back. They work the same way matching the behavior expected by @atruskie .

**Comment by antonfirsov** [comment]
If so, can't we just manually apply premultiplication in brush implementations?

For `SolidBrush` we can convert to `Vector4` instead of `TPixel` and multiply by `W` after the conversion.

In `ImageBrush` we can simply use `PixelConversionModifiers.Premultiply` when converting the overlay pixels to `Vector4`.

**Comment by JimBobSquarePants** [comment]
I'd have to revisit the code. It's been a while!

**Comment by JimBobSquarePants** [comment]
I've been having another look at this. 

The problem we are seeing is due to the conversion of `Color` to `TPixel` in ImageSharp. 

Internally this is performed by converting the `Rgba64` data representing the color into our `TPixel` type via `IPixel.FromRgba64`. This simply drops the alpha component. (_which matches the `TPixel` default behaviors_).

So we have a couple of options...

We can either:

1. Update `Color.ToPixel<TPixel>()` to premultiply by default for `TPixel` types without an alpha channel. This is a breaking change. 
2. Silently do the multiplication in all our applicators via an internal extension method.

I wish that I could do 1. It feels like the right thing to do since `Color` is a special type that we should be able to represent all `TPixel` types accurately with but I'm concerned about the breaking change. 2 requires us to remember to use the correct method in all locations.

Thoughts?

**Comment by JimBobSquarePants** [comment]
It occurs to me that new `Color(128,255,255,255)` would yield the expected result.

**Comment by tocsoft** [comment]
I doubt option 1 will cause much issue, (I doubt there are going to be too many people using `Color` intentionally using the fact alpha gets discarded)

I would argue the current behaviour is a bug and never intentional, so I feel just fixing it to perform pre-multiply across the board is the correct thing to do.. if we are particularly worried about people taking a dependency on a broken behaviour then we should add a global/static behaviour/feature flag to toggle on the old behaviour. (personally wouldn't actually bother with the feature flag unless we receive an reported issue that request an option to enable to old behaviour again)

**Comment by atruskie** [comment]
> It occurs to me that new `Color(128, 255, 255, 255)` would yield the expected result. 
> 

Forgive me if I'm wrong, but that'd only apply in the specific case where the background is black. What about every other case? E.g. background is green?

**Comment by JimBobSquarePants** [comment]
>I would argue the current behaviour is a bug and never intentional, so I feel just fixing it to perform pre-multiply across the board is the correct thing to do

@tocsoft I very much agree.

**Comment by JimBobSquarePants** [comment]
>Forgive me if I'm wrong, but that'd only apply in the specific case where the background is black. What about every other case? E.g. background is green?

@atruskie You're not wrong. 😄

**Comment by tocsoft** [comment]
example

We have an image with a red square on it and we draw Square `Green.Alpah(0.5)` shape half overlapping the first red shape with premultiplyng the color to a pixel prior to blending we would end up with:

![image](https://user-images.githubusercontent.com/166440/103468602-cb654200-4d52-11eb-82f4-7f28ae5be204.png)

but the output I would actually expect would be this:

![image](https://user-images.githubusercontent.com/166440/103468595-ba1c3580-4d52-11eb-90c9-d0ef22fc92c6.png)


its actually as though we need to expand `TPixel` types from variants without an alpha channel to one then has one before blending then convert it back again when updating the pixel buffer.

**Comment by atruskie** [comment]
@tocsoft , that's a great example. I'm on mobile so I can't confirm, but is the non-overlapping part of the green rectangle blended with the black background? I think it should be?

I think, conceptually this comes down to: for each pixel how does colour A add to colour B. Transparency is a valid component of a colour, so in my mind it's irrelevant what the target pixel is, because whatever target pixel that is there should be "converted" to a colour so it can be added to another colour. If I'm reading this right, that's what @tocsoft said in:

> its actually as though we need to expand TPixel types from variants without an alpha channel to one then has one before blending then convert it back again when updating the pixel buffer.

**Comment by JimBobSquarePants** [comment]
I don't actually think blending is the issue here, rather the expected result of a `Color => Rgb24` conversion.

In the original code example above we're using a solid color brush to draw over a black background (so no blending) but the result is unexpected since there was an explicit alpha value declaration. 

>its actually as though we need to expand `TPixel` types from variants without an alpha channel to one then has one before blending then convert it back again when updating the pixel buffer.

That's impossible since we've already lost the alpha component information on conversion from `Color` to `TPixel` if `TPixel` does not contain an alpha channel.

**Comment by atruskie** [comment]
@JimBobSquarePants that's a fair enough point. It depends on whether you 

a) are drawing by first converting everything to target image pixel format
b) or drawing in some higher level abstraction and then converting to target pixel format

Currently a is happening, and the transparency is being dropped before the operation occurs. This seems to be valid for drawing only in (a) mode.

However, it doesn't match expected behaviour, or how other libraries work (though caveat: haven't tested @tocsoft's recent example in other libraries)

**Comment by JimBobSquarePants** [comment]
@atruskie I can't really comment on how other libraries do things since I haven't investigated them deeply but our blend operations clearly work regardless of the `TPixel` format when we give them the instructions our API expects. 

I.E. 

Take a color and fill the region of interest with that color at a blend (_not percent, remind me to change that_) of `.5F`.

When we do the operations we're working with `Vector4` scanlines but they require a `TPixel` input since the operations are bound by that generic constraint. The input `TPixel` format has to be representative of what you want your `Vector4` to be.

The confusing, and difficult to choose the right answer for is how best to convert the `Color` abstraction to that format. 

- If I do `Vector4` to `Rgb24` I expect to lose the alpha component.
- If I do `Rgba32` to `Rgb24` I expect to lose the alpha component.

Should I expect `Color` to do differently?

**Comment by atruskie** [comment]
Ah that makes it much clearer for me. Sorry for the confusion.
I need to think about this a bit more.

**Comment by JimBobSquarePants** [comment]
I'm going to close this as I believe we have established that the result is expected.

https://github.com/SixLabors/ImageSharp.Drawing/issues/38#issuecomment-753550502

**Comment by atruskie** [comment]
@JimBobSquarePants, I think the technical aspect of this wandered but I do still think that the behaviour core to the issue is unexpected: When I paint with 50% opacity, I do NOT expect a fully opaque result.

If I'm understanding this correctly, it's due to a _silent_ truncation of an alpha value so that the drawing operation happens in the same pixel format as the resulting image. Really though, I'd expect either:

- the drawing operation to be invalid
- or the drawing operation to occur in a wider (with alpha) format and then converted at the end to the image format.

> I can't really comment on how other libraries do things

You did once see this example and agree it was strange: https://gist.github.com/atruskie/02f6fb35d6967c57ed543d109e83736e
Both of the examples in the gist are drawn on image formats are 24-bit and without alpha, and both render a blended square.

| ImageSharp | System.Drawing | SkiaSharp |
|--------------|-------------------|-------------|
|![rgb24demo](https://user-images.githubusercontent.com/1452968/125184607-90444e00-e262-11eb-9e65-bfa053c6a22e.png)|![](https://gist.github.com/atruskie/02f6fb35d6967c57ed543d109e83736e/raw/5bd82b465ccb252401711c1fda8cff1e82975b33/sdTestBlending.png)|![](https://gist.github.com/atruskie/02f6fb35d6967c57ed543d109e83736e/raw/5bd82b465ccb252401711c1fda8cff1e82975b33/skiaTestBlending.png)|

I get that ImageSharp is _not_ System.Drawing but I think it's important that common operations behave in expected ways.

**Comment by JimBobSquarePants** [comment]
Hi @atruskie  I'll try to explain everything the best I can. 

>You did once see this example and agree it was strange

Yes, but that was a mistake on my part and I'm sorry about that. There's a lot of theory to remember across all these APIs and sometimes I will  confuse myself.

>I think the technical aspect of this wandered but I do still think that the behavior core to the issue is unexpected: When I paint with 50% opacity, I do NOT expect a fully opaque result.

What `System.Drawing` and `SkiaSharp` both do is take how **opaque** a given color is and uses that as a measure of how much to **blend** two colors. That's a management of a certain expectation (_to the detriment of accuracy_) and while that may work for their limited APIs it doesn't for APIs that offer the full complement of color blending and alpha composition modes like we do.

Given my example earlier you will see that when you explicitly tell the `Fill` method to use a blend (_We really must rename that property_) percentage of 50% at `.5F` you get a correct blend of two opaque colors.

```c#
public void Test()
{
    using var image = new Image<Rgb24>(Configuration.Default, 100, 100, Color.Black);
    var o = new GraphicsOptions { BlendPercentage = .5F }; // This is how much to mix the colors.
    image.Mutate(x => x.Fill(o, Color.Red));

    // 50% blended with black
    var expectedColor = new Rgb24(128, 0, 0);

    Assert.Equal(expectedColor, image[50, 50]);
}
```

>If I'm understanding this correctly, it's due to a silent truncation of an alpha value so that the drawing operation happens in the same pixel format as the resulting image.

Now there's truncation yes, from `Color` to `Rgb24` but this is absolutely correct behavior. The `RGB` colorspaces do not have any representation of opacity. (_Incidentally the `A` component of `RGBA` is not part of any colorspace either_). We cannot preserve that alpha component because there is simply nowhere to house it in the chosen pixel format. It also doesn't affect how much two colors are blended. Only `BlendPercentage` does that.

Truncation of alpha is common. You can see that if you save a jpeg with `System.Drawing` containing a non-opaque color with a `Bitmap` of pixel format `Format32bppArgb`. `Color.Transparent` becomes` Color.White`, `Color.Empty` becomes `Color.Black`.

>I get that ImageSharp is not System.Drawing but I think it's important that common operations behave in expected ways.

We cannot, and should not do what `System.Drawing` and `SkiaSharp` do in this regard. By making assumptions we introduce unexpected and incorrect behavior. 

Take for example our given color `Rgb32(255, 0, 0, 128)`. If we explicitly set the `BlendPercentage` to a value other that `1F` and blend that color in an image of pixel format `Rgba32` what value should take precedence? Should we ignore the alpha component, use that exclusively, or use both?

The correct answer of course is to take the **full available component** set of the given pixel format and use our `BlendPercentage` to determine how much to blend the color with our background. This is exactly what we do.

So... All that said. Here is how you would do a 50% blend of two opaque colors with the latest ImageSharp.Drawing API.

```c#
using var image = new Image<Rgb24>(Configuration.Default, 100, 100, Color.Black);
var options = new DrawingOptions
{
    GraphicsOptions = new GraphicsOptions { BlendPercentage = .5F }
}; 

image.Mutate(x => x.Fill(options, Color.Red, new RectangleF(10, 10, 80, 80)));

image.Save("issue-38.png");
```

![issue-38](https://user-images.githubusercontent.com/385879/125194011-4e59de80-e247-11eb-9bae-8cca6b80170f.png)

**Comment by atruskie** [comment]
Wow thanks for explaining in such detail. Thank you. And yeah of course, there is a lot to remember. I clearly can't keep track of it.

I can appreciate the miss-use of the alpha channel by the other libraries.

In terms of muscle memory and simplicity of encoding opacity in the alpha component (which we rely _heavily_ on our app and config files), it is sad that such a useful convention is not as easily representable. 

> Take for example our given color Rgb32(255, 0, 0, 128). If we explicitly set the BlendPercentage to a value other that 1F and blend that color in an image of pixel format Rgba32 what value should take precedence? Should we ignore the alpha component, use that exclusively, or use both?

My naive presumption is you would use both, i.e. the alpha would be multiplied by the `BlendPercentage`. The way I had previously rationalised `BlendPercentage` was that it was a complementary secondary filter that was intended to be used in different scenarios. For example:

- draw with an alpha solid brush when painting 2d graphics (intended transparency)
- draw with a `BlendPercentage` when overlaying an image (i.e. a blob of pixels of unknown transparency) on another

This rationalization was of course done through what I'd previously has experience with, which was the less-accurate System.Drawing behaviour.

> Truncation of alpha is common. You can see that if you save a jpeg with System.Drawing containing a non-opaque color with a Bitmap of pixel format Format32bppArgb. Color.Transparent becomes Color.White, Color.Empty becomes Color.Black.

Logical or not, yes, I fully expect _that_ truncation. There is no way to store that data.

I don't expect a 2D drawing operation to have the alpha truncated until 'pen gets to paper' as it were. As in, transparent color should be transparent colour, right until the final result is saved into the scanline buffer. 

> Here is how you would do a 50% blend of two opaque colors with the latest ImageSharp.Drawing API

Indeed, I have an extension method that does just that 😄 

https://github.com/QutEcoacoustics/audio-analysis/blob/e1a6784f4104aad7aa44d3b736d442295b584a99/src/Acoustics.Shared/ImageSharp/ImageSharpExtensions.cs#L241-L282

Since this won't be changed, I'll clean-up that method so it explains to my future self the subtleties of this...
